"""ISO 3166-1 country code mappings.

Provides lookups between alpha-2, alpha-3 codes and country names.
"""

# Mapping: alpha_2 -> {'alpha_3': str, 'name': str}
COUNTRIES_BY_ALPHA2 = {
    'AD': {'alpha_3': 'AND', 'name': 'Andorra'},
    'AE': {'alpha_3': 'ARE', 'name': 'United Arab Emirates'},
    'AF': {'alpha_3': 'AFG', 'name': 'Afghanistan'},
    'AG': {'alpha_3': 'ATG', 'name': 'Antigua and Barbuda'},
    'AI': {'alpha_3': 'AIA', 'name': 'Anguilla'},
    'AL': {'alpha_3': 'ALB', 'name': 'Albania'},
    'AM': {'alpha_3': 'ARM', 'name': 'Armenia'},
    'AO': {'alpha_3': 'AGO', 'name': 'Angola'},
    'AQ': {'alpha_3': 'ATA', 'name': 'Antarctica'},
    'AR': {'alpha_3': 'ARG', 'name': 'Argentina'},
    'AS': {'alpha_3': 'ASM', 'name': 'American Samoa'},
    'AT': {'alpha_3': 'AUT', 'name': 'Austria'},
    'AU': {'alpha_3': 'AUS', 'name': 'Australia'},
    'AW': {'alpha_3': 'ABW', 'name': 'Aruba'},
    'AX': {'alpha_3': 'ALA', 'name': 'Åland Islands'},
    'AZ': {'alpha_3': 'AZE', 'name': 'Azerbaijan'},
    'BA': {'alpha_3': 'BIH', 'name': 'Bosnia and Herzegovina'},
    'BB': {'alpha_3': 'BRB', 'name': 'Barbados'},
    'BD': {'alpha_3': 'BGD', 'name': 'Bangladesh'},
    'BE': {'alpha_3': 'BEL', 'name': 'Belgium'},
    'BF': {'alpha_3': 'BFA', 'name': 'Burkina Faso'},
    'BG': {'alpha_3': 'BGR', 'name': 'Bulgaria'},
    'BH': {'alpha_3': 'BHR', 'name': 'Bahrain'},
    'BI': {'alpha_3': 'BDI', 'name': 'Burundi'},
    'BJ': {'alpha_3': 'BEN', 'name': 'Benin'},
    'BL': {'alpha_3': 'BLM', 'name': 'Saint Barthélemy'},
    'BM': {'alpha_3': 'BMU', 'name': 'Bermuda'},
    'BN': {'alpha_3': 'BRN', 'name': 'Brunei'},
    'BO': {'alpha_3': 'BOL', 'name': 'Bolivia'},
    'BQ': {'alpha_3': 'BES', 'name': 'Bonaire, Sint Eustatius and Saba'},
    'BR': {'alpha_3': 'BRA', 'name': 'Brazil'},
    'BS': {'alpha_3': 'BHS', 'name': 'Bahamas'},
    'BT': {'alpha_3': 'BTN', 'name': 'Bhutan'},
    'BV': {'alpha_3': 'BVT', 'name': 'Bouvet Island'},
    'BW': {'alpha_3': 'BWA', 'name': 'Botswana'},
    'BY': {'alpha_3': 'BLR', 'name': 'Belarus'},
    'BZ': {'alpha_3': 'BLZ', 'name': 'Belize'},
    'CA': {'alpha_3': 'CAN', 'name': 'Canada'},
    'CC': {'alpha_3': 'CCK', 'name': 'Cocos (Keeling) Islands'},
    'CD': {'alpha_3': 'COD', 'name': 'Democratic Republic of the Congo'},
    'CF': {'alpha_3': 'CAF', 'name': 'Central African Republic'},
    'CG': {'alpha_3': 'COG', 'name': 'Congo'},
    'CH': {'alpha_3': 'CHE', 'name': 'Switzerland'},
    'CI': {'alpha_3': 'CIV', 'name': "Côte d'Ivoire"},
    'CK': {'alpha_3': 'COK', 'name': 'Cook Islands'},
    'CL': {'alpha_3': 'CHL', 'name': 'Chile'},
    'CM': {'alpha_3': 'CMR', 'name': 'Cameroon'},
    'CN': {'alpha_3': 'CHN', 'name': 'China'},
    'CO': {'alpha_3': 'COL', 'name': 'Colombia'},
    'CR': {'alpha_3': 'CRI', 'name': 'Costa Rica'},
    'CU': {'alpha_3': 'CUB', 'name': 'Cuba'},
    'CV': {'alpha_3': 'CPV', 'name': 'Cabo Verde'},
    'CW': {'alpha_3': 'CUW', 'name': 'Curaçao'},
    'CX': {'alpha_3': 'CXR', 'name': 'Christmas Island'},
    'CY': {'alpha_3': 'CYP', 'name': 'Cyprus'},
    'CZ': {'alpha_3': 'CZE', 'name': 'Czechia'},
    'DE': {'alpha_3': 'DEU', 'name': 'Germany'},
    'DJ': {'alpha_3': 'DJI', 'name': 'Djibouti'},
    'DK': {'alpha_3': 'DNK', 'name': 'Denmark'},
    'DM': {'alpha_3': 'DMA', 'name': 'Dominica'},
    'DO': {'alpha_3': 'DOM', 'name': 'Dominican Republic'},
    'DZ': {'alpha_3': 'DZA', 'name': 'Algeria'},
    'EC': {'alpha_3': 'ECU', 'name': 'Ecuador'},
    'EE': {'alpha_3': 'EST', 'name': 'Estonia'},
    'EG': {'alpha_3': 'EGY', 'name': 'Egypt'},
    'EH': {'alpha_3': 'ESH', 'name': 'Western Sahara'},
    'ER': {'alpha_3': 'ERI', 'name': 'Eritrea'},
    'ES': {'alpha_3': 'ESP', 'name': 'Spain'},
    'ET': {'alpha_3': 'ETH', 'name': 'Ethiopia'},
    'FI': {'alpha_3': 'FIN', 'name': 'Finland'},
    'FJ': {'alpha_3': 'FJI', 'name': 'Fiji'},
    'FK': {'alpha_3': 'FLK', 'name': 'Falkland Islands'},
    'FM': {'alpha_3': 'FSM', 'name': 'Micronesia'},
    'FO': {'alpha_3': 'FRO', 'name': 'Faroe Islands'},
    'FR': {'alpha_3': 'FRA', 'name': 'France'},
    'GA': {'alpha_3': 'GAB', 'name': 'Gabon'},
    'GB': {'alpha_3': 'GBR', 'name': 'United Kingdom'},
    'GD': {'alpha_3': 'GRD', 'name': 'Grenada'},
    'GE': {'alpha_3': 'GEO', 'name': 'Georgia'},
    'GF': {'alpha_3': 'GUF', 'name': 'French Guiana'},
    'GG': {'alpha_3': 'GGY', 'name': 'Guernsey'},
    'GH': {'alpha_3': 'GHA', 'name': 'Ghana'},
    'GI': {'alpha_3': 'GIB', 'name': 'Gibraltar'},
    'GL': {'alpha_3': 'GRL', 'name': 'Greenland'},
    'GM': {'alpha_3': 'GMB', 'name': 'Gambia'},
    'GN': {'alpha_3': 'GIN', 'name': 'Guinea'},
    'GP': {'alpha_3': 'GLP', 'name': 'Guadeloupe'},
    'GQ': {'alpha_3': 'GNQ', 'name': 'Equatorial Guinea'},
    'GR': {'alpha_3': 'GRC', 'name': 'Greece'},
    'GS': {'alpha_3': 'SGS', 'name': 'South Georgia and the South Sandwich Islands'},
    'GT': {'alpha_3': 'GTM', 'name': 'Guatemala'},
    'GU': {'alpha_3': 'GUM', 'name': 'Guam'},
    'GW': {'alpha_3': 'GNB', 'name': 'Guinea-Bissau'},
    'GY': {'alpha_3': 'GUY', 'name': 'Guyana'},
    'HK': {'alpha_3': 'HKG', 'name': 'Hong Kong'},
    'HM': {'alpha_3': 'HMD', 'name': 'Heard Island and McDonald Islands'},
    'HN': {'alpha_3': 'HND', 'name': 'Honduras'},
    'HR': {'alpha_3': 'HRV', 'name': 'Croatia'},
    'HT': {'alpha_3': 'HTI', 'name': 'Haiti'},
    'HU': {'alpha_3': 'HUN', 'name': 'Hungary'},
    'ID': {'alpha_3': 'IDN', 'name': 'Indonesia'},
    'IE': {'alpha_3': 'IRL', 'name': 'Ireland'},
    'IL': {'alpha_3': 'ISR', 'name': 'Israel'},
    'IM': {'alpha_3': 'IMN', 'name': 'Isle of Man'},
    'IN': {'alpha_3': 'IND', 'name': 'India'},
    'IO': {'alpha_3': 'IOT', 'name': 'British Indian Ocean Territory'},
    'IQ': {'alpha_3': 'IRQ', 'name': 'Iraq'},
    'IR': {'alpha_3': 'IRN', 'name': 'Iran'},
    'IS': {'alpha_3': 'ISL', 'name': 'Iceland'},
    'IT': {'alpha_3': 'ITA', 'name': 'Italy'},
    'JE': {'alpha_3': 'JEY', 'name': 'Jersey'},
    'JM': {'alpha_3': 'JAM', 'name': 'Jamaica'},
    'JO': {'alpha_3': 'JOR', 'name': 'Jordan'},
    'JP': {'alpha_3': 'JPN', 'name': 'Japan'},
    'KE': {'alpha_3': 'KEN', 'name': 'Kenya'},
    'KG': {'alpha_3': 'KGZ', 'name': 'Kyrgyzstan'},
    'KH': {'alpha_3': 'KHM', 'name': 'Cambodia'},
    'KI': {'alpha_3': 'KIR', 'name': 'Kiribati'},
    'KM': {'alpha_3': 'COM', 'name': 'Comoros'},
    'KN': {'alpha_3': 'KNA', 'name': 'Saint Kitts and Nevis'},
    'KP': {'alpha_3': 'PRK', 'name': 'North Korea'},
    'KR': {'alpha_3': 'KOR', 'name': 'South Korea'},
    'KW': {'alpha_3': 'KWT', 'name': 'Kuwait'},
    'KY': {'alpha_3': 'CYM', 'name': 'Cayman Islands'},
    'KZ': {'alpha_3': 'KAZ', 'name': 'Kazakhstan'},
    'LA': {'alpha_3': 'LAO', 'name': 'Laos'},
    'LB': {'alpha_3': 'LBN', 'name': 'Lebanon'},
    'LC': {'alpha_3': 'LCA', 'name': 'Saint Lucia'},
    'LI': {'alpha_3': 'LIE', 'name': 'Liechtenstein'},
    'LK': {'alpha_3': 'LKA', 'name': 'Sri Lanka'},
    'LR': {'alpha_3': 'LBR', 'name': 'Liberia'},
    'LS': {'alpha_3': 'LSO', 'name': 'Lesotho'},
    'LT': {'alpha_3': 'LTU', 'name': 'Lithuania'},
    'LU': {'alpha_3': 'LUX', 'name': 'Luxembourg'},
    'LV': {'alpha_3': 'LVA', 'name': 'Latvia'},
    'LY': {'alpha_3': 'LBY', 'name': 'Libya'},
    'MA': {'alpha_3': 'MAR', 'name': 'Morocco'},
    'MC': {'alpha_3': 'MCO', 'name': 'Monaco'},
    'MD': {'alpha_3': 'MDA', 'name': 'Moldova'},
    'ME': {'alpha_3': 'MNE', 'name': 'Montenegro'},
    'MF': {'alpha_3': 'MAF', 'name': 'Saint Martin'},
    'MG': {'alpha_3': 'MDG', 'name': 'Madagascar'},
    'MH': {'alpha_3': 'MHL', 'name': 'Marshall Islands'},
    'MK': {'alpha_3': 'MKD', 'name': 'North Macedonia'},
    'ML': {'alpha_3': 'MLI', 'name': 'Mali'},
    'MM': {'alpha_3': 'MMR', 'name': 'Myanmar'},
    'MN': {'alpha_3': 'MNG', 'name': 'Mongolia'},
    'MO': {'alpha_3': 'MAC', 'name': 'Macao'},
    'MP': {'alpha_3': 'MNP', 'name': 'Northern Mariana Islands'},
    'MQ': {'alpha_3': 'MTQ', 'name': 'Martinique'},
    'MR': {'alpha_3': 'MRT', 'name': 'Mauritania'},
    'MS': {'alpha_3': 'MSR', 'name': 'Montserrat'},
    'MT': {'alpha_3': 'MLT', 'name': 'Malta'},
    'MU': {'alpha_3': 'MUS', 'name': 'Mauritius'},
    'MV': {'alpha_3': 'MDV', 'name': 'Maldives'},
    'MW': {'alpha_3': 'MWI', 'name': 'Malawi'},
    'MX': {'alpha_3': 'MEX', 'name': 'Mexico'},
    'MY': {'alpha_3': 'MYS', 'name': 'Malaysia'},
    'MZ': {'alpha_3': 'MOZ', 'name': 'Mozambique'},
    'NA': {'alpha_3': 'NAM', 'name': 'Namibia'},
    'NC': {'alpha_3': 'NCL', 'name': 'New Caledonia'},
    'NE': {'alpha_3': 'NER', 'name': 'Niger'},
    'NF': {'alpha_3': 'NFK', 'name': 'Norfolk Island'},
    'NG': {'alpha_3': 'NGA', 'name': 'Nigeria'},
    'NI': {'alpha_3': 'NIC', 'name': 'Nicaragua'},
    'NL': {'alpha_3': 'NLD', 'name': 'Netherlands'},
    'NO': {'alpha_3': 'NOR', 'name': 'Norway'},
    'NP': {'alpha_3': 'NPL', 'name': 'Nepal'},
    'NR': {'alpha_3': 'NRU', 'name': 'Nauru'},
    'NU': {'alpha_3': 'NIU', 'name': 'Niue'},
    'NZ': {'alpha_3': 'NZL', 'name': 'New Zealand'},
    'OM': {'alpha_3': 'OMN', 'name': 'Oman'},
    'PA': {'alpha_3': 'PAN', 'name': 'Panama'},
    'PE': {'alpha_3': 'PER', 'name': 'Peru'},
    'PF': {'alpha_3': 'PYF', 'name': 'French Polynesia'},
    'PG': {'alpha_3': 'PNG', 'name': 'Papua New Guinea'},
    'PH': {'alpha_3': 'PHL', 'name': 'Philippines'},
    'PK': {'alpha_3': 'PAK', 'name': 'Pakistan'},
    'PL': {'alpha_3': 'POL', 'name': 'Poland'},
    'PM': {'alpha_3': 'SPM', 'name': 'Saint Pierre and Miquelon'},
    'PN': {'alpha_3': 'PCN', 'name': 'Pitcairn'},
    'PR': {'alpha_3': 'PRI', 'name': 'Puerto Rico'},
    'PS': {'alpha_3': 'PSE', 'name': 'Palestine'},
    'PT': {'alpha_3': 'PRT', 'name': 'Portugal'},
    'PW': {'alpha_3': 'PLW', 'name': 'Palau'},
    'PY': {'alpha_3': 'PRY', 'name': 'Paraguay'},
    'QA': {'alpha_3': 'QAT', 'name': 'Qatar'},
    'RE': {'alpha_3': 'REU', 'name': 'Réunion'},
    'RO': {'alpha_3': 'ROU', 'name': 'Romania'},
    'RS': {'alpha_3': 'SRB', 'name': 'Serbia'},
    'RU': {'alpha_3': 'RUS', 'name': 'Russia'},
    'RW': {'alpha_3': 'RWA', 'name': 'Rwanda'},
    'SA': {'alpha_3': 'SAU', 'name': 'Saudi Arabia'},
    'SB': {'alpha_3': 'SLB', 'name': 'Solomon Islands'},
    'SC': {'alpha_3': 'SYC', 'name': 'Seychelles'},
    'SD': {'alpha_3': 'SDN', 'name': 'Sudan'},
    'SE': {'alpha_3': 'SWE', 'name': 'Sweden'},
    'SG': {'alpha_3': 'SGP', 'name': 'Singapore'},
    'SH': {'alpha_3': 'SHN', 'name': 'Saint Helena'},
    'SI': {'alpha_3': 'SVN', 'name': 'Slovenia'},
    'SJ': {'alpha_3': 'SJM', 'name': 'Svalbard and Jan Mayen'},
    'SK': {'alpha_3': 'SVK', 'name': 'Slovakia'},
    'SL': {'alpha_3': 'SLE', 'name': 'Sierra Leone'},
    'SM': {'alpha_3': 'SMR', 'name': 'San Marino'},
    'SN': {'alpha_3': 'SEN', 'name': 'Senegal'},
    'SO': {'alpha_3': 'SOM', 'name': 'Somalia'},
    'SR': {'alpha_3': 'SUR', 'name': 'Suriname'},
    'SS': {'alpha_3': 'SSD', 'name': 'South Sudan'},
    'ST': {'alpha_3': 'STP', 'name': 'São Tomé and Príncipe'},
    'SV': {'alpha_3': 'SLV', 'name': 'El Salvador'},
    'SX': {'alpha_3': 'SXM', 'name': 'Sint Maarten'},
    'SY': {'alpha_3': 'SYR', 'name': 'Syria'},
    'SZ': {'alpha_3': 'SWZ', 'name': 'Eswatini'},
    'TC': {'alpha_3': 'TCA', 'name': 'Turks and Caicos Islands'},
    'TD': {'alpha_3': 'TCD', 'name': 'Chad'},
    'TF': {'alpha_3': 'ATF', 'name': 'French Southern Territories'},
    'TG': {'alpha_3': 'TGO', 'name': 'Togo'},
    'TH': {'alpha_3': 'THA', 'name': 'Thailand'},
    'TJ': {'alpha_3': 'TJK', 'name': 'Tajikistan'},
    'TK': {'alpha_3': 'TKL', 'name': 'Tokelau'},
    'TL': {'alpha_3': 'TLS', 'name': 'Timor-Leste'},
    'TM': {'alpha_3': 'TKM', 'name': 'Turkmenistan'},
    'TN': {'alpha_3': 'TUN', 'name': 'Tunisia'},
    'TO': {'alpha_3': 'TON', 'name': 'Tonga'},
    'TR': {'alpha_3': 'TUR', 'name': 'Turkey'},
    'TT': {'alpha_3': 'TTO', 'name': 'Trinidad and Tobago'},
    'TV': {'alpha_3': 'TUV', 'name': 'Tuvalu'},
    'TW': {'alpha_3': 'TWN', 'name': 'Taiwan'},
    'TZ': {'alpha_3': 'TZA', 'name': 'Tanzania'},
    'UA': {'alpha_3': 'UKR', 'name': 'Ukraine'},
    'UG': {'alpha_3': 'UGA', 'name': 'Uganda'},
    'UM': {'alpha_3': 'UMI', 'name': 'United States Minor Outlying Islands'},
    'US': {'alpha_3': 'USA', 'name': 'United States'},
    'UY': {'alpha_3': 'URY', 'name': 'Uruguay'},
    'UZ': {'alpha_3': 'UZB', 'name': 'Uzbekistan'},
    'VA': {'alpha_3': 'VAT', 'name': 'Vatican City'},
    'VC': {'alpha_3': 'VCT', 'name': 'Saint Vincent and the Grenadines'},
    'VE': {'alpha_3': 'VEN', 'name': 'Venezuela'},
    'VG': {'alpha_3': 'VGB', 'name': 'Virgin Islands, British'},
    'VI': {'alpha_3': 'VIR', 'name': 'Virgin Islands, U.S.'},
    'VN': {'alpha_3': 'VNM', 'name': 'Vietnam'},
    'VU': {'alpha_3': 'VUT', 'name': 'Vanuatu'},
    'WF': {'alpha_3': 'WLF', 'name': 'Wallis and Futuna'},
    'WS': {'alpha_3': 'WSM', 'name': 'Samoa'},
    'YE': {'alpha_3': 'YEM', 'name': 'Yemen'},
    'YT': {'alpha_3': 'MYT', 'name': 'Mayotte'},
    'ZA': {'alpha_3': 'ZAF', 'name': 'South Africa'},
    'ZM': {'alpha_3': 'ZMB', 'name': 'Zambia'},
    'ZW': {'alpha_3': 'ZWE', 'name': 'Zimbabwe'},
}

# Reverse mapping: alpha_3 -> alpha_2 (for efficient lookups by alpha_3)
COUNTRIES_BY_ALPHA3 = {v['alpha_3']: k for k, v in COUNTRIES_BY_ALPHA2.items()}


def get_country_name_by_alpha2(country_code: str) -> str | None:
    """Get country name from alpha-2 code, or None if not found."""
    entry = COUNTRIES_BY_ALPHA2.get(country_code)
    return entry['name'] if entry else None


def get_alpha2_by_alpha3(country_code: str) -> str | None:
    """Get alpha-2 code from alpha-3 code, or None if not found."""
    return COUNTRIES_BY_ALPHA3.get(country_code)


__all__ = [
    'COUNTRIES_BY_ALPHA2',
    'COUNTRIES_BY_ALPHA3',
    'get_alpha2_by_alpha3',
    'get_country_name_by_alpha2',
]
